### ISSUE TITLE
Open Web App

### ISSUE THREAD

**Issue by Mte90** [boyofgreen/ManUp.js#1]
Firefox/OS/for Adnroid follow the Open Web App, this lbirary is not compatible with this standard so the actual browser of Mozilla not work.
https://developer.mozilla.org/en-US/Apps/Build/Manifest
The API of Mozilla require a real file with the correct JSON data and the mozApps class for install.

**Comment by boyofgreen** [comment]
Hey Daniele, So what I'm trying to solve in this library, is a polyfill for the manifest for web apps, which I believe Mozilla is implementing as well: https://bugzilla.mozilla.org/show_bug.cgi?id=997779  This is more for installable web apps from the browser rather than the markets.  Right now it works on FFOS devices by reading the manifest and creating the meta tags when necessary.  Is there part of this I'm missing?

**Comment by Mte90** [comment]
On Firefox OS 2.2 simulator when i go to the demo page not work.
Firefox OS 2.2 and below not support this standard so your polyfill not work.
If you see on https://github.com/robnyman/Firefox-OS-Boilerplate-App this use the open web app standard supported on gecko system.
If you open the demo with firefox and lick on the + icon on the right the code of open web app is executed for install the app.
The open web app standard is born before the w3c standards.

**Comment by boyofgreen** [comment]
Sorry Bro, that just isn't the problem I'm trying to solve.  Closing the issue.
